import "./globals.css";
import { EB_Garamond, Inter } from "next/font/google";
import Footer from "@/layouts/footer/Footer";
import Provider from "./Provider";
import Header from "@/layouts/header/Header";
import PageLoadingIndicator from "./PageLoadingIndicator";

export const garamond = EB_Garamond({
  subsets: ["latin"],
  weight: ["700", "600", "500", "400"],
  variable: "--font-garamond",
  display: "swap",
});

export const inter = Inter({
  subsets: ["latin"],
  weight: ["700", "600", "500", "400"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko" className={`${garamond.variable} ${inter.variable}`}>
      <body>
        <Provider>
          {/* @ts-expect-error Async Server Component */}
          <Header />
          <section className="contents">
            <PageLoadingIndicator />
            {children}
          </section>
          <Footer />
        </Provider>
        <div id={"portal"} />
      </body>
    </html>
  );
}
