import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";
import Footer from "@/layouts/footer/Footer";
import Provider from "./Provider";
import Header from "@/layouts/header/Header";
import PageLoadingIndicator from "./PageLoadingIndicator";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["700", "500", "400", "300"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <body className={notoSansKR.className}>
        <Provider>
          {/* @ts-expect-error Async Server Component */}
          <Header />
          <section className="contents">
            <PageLoadingIndicator />
            {children}
          </section>
          <Footer />
        </Provider>
        <div id={"portal"} />
      </body>
    </html>
  );
}
